# This is a config for E2B sandbox template.
# You can use template ID (pb40k2antt5z7pbxvxz4) or template name (vibe-nextjs-development-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-development-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-development-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-development-2')

team_id = "078a0a7f-b9eb-4f69-9a25-9918d5fadf1a"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-development-2"
template_id = "pb40k2antt5z7pbxvxz4"
